{% set name = "seqforge" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ERBringHorvath/SeqForge/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5dc5401c05a4c08bee3ac3b7ea59316ea028d8de3eaf4cdb33f3ef7902d662e3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - biopython
    - pandas
    - matplotlib-base
    - blast
    - seaborn
    - logomaker

test:
  requires:
    - python
    - pip
  commands:
    - python -c "import sys; import seqforge; print('ok')"
    - seqforge --version
    - seqforge --module-health

    - python - <<'PY'
from pathlib import pathlib
p  = Path("tmp.fa")
p.write_text(">a\nACGT\n>b\nACGT\n")
import subprocess, os
os.makedirs("out", exist_ok=True)
r = subprocess.run(["seqforge","unique-headers","-f","tmp.fa","-o","--progress","none"], check=True)
out = Path("out") / "temp.fa"
print(out.read_text())
print("OK")
PY

about:
  home: https://github.com/ERBringHorvath/SeqForge
  license: matplotlib
  license_family: MIT
  license_file: license
  summary: "SeqForge: A genomics toolkit for FASTA processing, BLAST orchestration, and motif mining."
  description: |
    SeqForge provides utilities to sanitize, split, annotate, and analyze FASTA files; run BLAST+ queries 
    in parallel; and perform motif mining with export options. Progress reporting is handled by an in-house 
    progress bar.

extra:
  recipe-maintainters:
    - ERBringHorvath